In [1]:
import numpy as np

In [4]:
num=np.array([1,2,'rahul',5])
num

array(['1', '2', 'rahul', '5'], dtype='<U11')

In [6]:
type(num)

numpy.ndarray

In [11]:
#Upcasting: 
num=np.array([1,2,5.0])
(num)

array([1., 2., 5.])

In [16]:
#two dimensions
num=np.array([[1,2,3],(4,5,8)])
num

array([[1, 2, 3],
       [4, 5, 8]])

In [19]:
#Minimum dimensions 2:
np.array([1, 2, 3], ndmin=3)

array([[[1, 2, 3]]])

In [22]:
#dtype
np.array((1,2),dtype=bool)

array([ True,  True])

In [24]:
#dtype
np.array((1,2),dtype=float)

array([1., 2.])

In [7]:
#Data-type consisting of more than one element:
x = np.array([(1,2),(3,4)],dtype=[('a','float'),('b','complex')])
x

array([(1., 2.+0.j), (3., 4.+0.j)], dtype=[('a', '<f8'), ('b', '<c16')])

In [8]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [14]:
a=type(x[0][0])
b=type(x[0][1])
a,b

(numpy.int16, numpy.int64)

Matrix is a sub-classe of an array
we can create matrix from array as belows:

In [33]:
r= np.array([((1,3),(2,9))],ndmin=3)
r

array([[[1, 3],
        [2, 9]]])

In [34]:
np.mat(r)

matrix([[1, 3],
        [2, 9]])

# numpy.asarray


In [1]:
#Convert the input to an array.

In [2]:
 a = [1, 2]
type(a)

list

In [5]:
type(np.asarray(a))

numpy.ndarray

In [6]:
np.asarray((1,2))

array([1, 2])

In [15]:
#If dtype is set, array is copied only if dtype does not match:
a = np.array([1, 2])
a

array([1, 2])

In [21]:
type(a)


numpy.ndarray

In [42]:
b = np.asarray([1,2])
b
type(b)

numpy.ndarray

In [32]:
b is  a
    

False

ASANYARRAY-
it is used to convert nonarray data to array format.
it will not convert array data(like matrix) to array form as it is already an varience of array

In [33]:
A=(1,5)
type(A)

tuple

In [34]:
np.asanyarray(A)

array([1, 5])

In [37]:
b=np.mat([1,8])
b

matrix([[1, 8]])

In [38]:
np.asanyarray(b)

matrix([[1, 8]])

deep copy and swallow copy

In [53]:
a=np.array([1,5])
a

array([1, 5])

In [54]:
n=a    #this is a swallow copy

In [55]:
n

array([1, 5])

In [58]:
n[0] = 14

In [59]:
n

array([14,  5])

In [60]:
a

array([14,  5])

In [57]:
z = np.copy(a)       #this is a eg of deep copy.
z

array([1, 5])

In [61]:
z[0]= 87

In [62]:
z

array([87,  5])

In [63]:
a

array([14,  5])

numpy.fromfunction
#Construct an array by executing a function over each coordinate.

In [2]:
np.fromfunction(lambda i,j:i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [4]:
np.fromfunction(lambda i,j:i+j ,(3,3),dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#Create a new 1-dimensional array from an iterable object.

In [6]:
r= np.fromiter(range(5),dtype=int)
r

array([0, 1, 2, 3, 4])

In [7]:
#A new 1-D array initialized from text data in a string

In [8]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [10]:
a = np.fromstring('1,2',sep=', ')
a

array([1., 2.])

In [11]:
# How to create create a record array from a (flat) list of arrays

In [12]:
x1=np.array([1,2,3,4])
x2=np.array([2.,7.,8.,4])
x3=np.array(['a','dd','xyz','12'])

In [13]:
t=np.core.records.fromarrays([x1,x2,x3],names='a,b,c,d')

In [14]:
t

rec.array([(1, 2., 'a'), (2, 7., 'dd'), (3, 8., 'xyz'), (4, 4., '12')],
          dtype=[('a', '<i4'), ('b', '<f8'), ('c', '<U3')])

In [15]:
type(t)

numpy.recarray

In [20]:
type(t[0][1])

numpy.float64

In [24]:
my_list=[1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [25]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


arange and linspace

In [2]:
import numpy as np

In [7]:
np.arange(5,20,2.8)

array([ 5. ,  7.8, 10.6, 13.4, 16.2, 19. ])

In [6]:
a=list(np.arange(2,20,2.4))
type(a)

list

In [11]:
print("Numbers spaced apart by 5:",np.arange(50,-30,-5))

Numbers spaced apart by 5: [ 50  45  40  35  30  25  20  15  10   5   0  -5 -10 -15 -20 -25]


In [12]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


linspace- in below example,linspace divides data equally between given range (1 to 5) in 10 values.

In [14]:
print("linearly spaced numbers between 1 and 5\n--------------------------------------------")
np.linspace(1,5,10)

linearly spaced numbers between 1 and 5
--------------------------------------------


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [3]:
#difference between arange and linspance

import numpy as np
np_array = np.linspace(0,11,5)
print(np_array)
np_array = np.arange(0,11,5)
print(np_array)

[ 0.    2.75  5.5   8.25 11.  ]
[ 0  5 10]


#Matrix creation

In [17]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [22]:
print("Matrix of zeroes\n--------------------")
e = (np.zeros((3,4))) # Notice Tuples
type(e)
print(e)

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [24]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [29]:
print("Matrix of 5's\n---------------------")
e = np.ones((3,5))
e+5

Matrix of 5's
---------------------


array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [33]:
np.zeros((3,4,8))+5*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [35]:
np.empty((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(3)+1

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [41]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [42]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [45]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [4]:
#reshape function- you are allowed to enter values in multiple of max value.i.e if 0,16 then (8,2) or (4,4,2)

In [7]:
a = np.arange(0,16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [9]:
a.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [13]:
a.reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [14]:
a.reshape(-1,4)  # here -1 is consider as 4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
a.reshape(2,8)  # here -1 is consider as 8

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [16]:
#Extract a diagonal or construct a diagonal array.

In [22]:
x = np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.diag(x)

array([ 0,  5, 10, 15])

In [24]:
np.diag(x,k=1)

array([ 1,  6, 11])

In [25]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [27]:
np.diag(x,k=-3)

array([12])

In [28]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [29]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [31]:
np.diagflat([[1,2],[3,4],[5,9]])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 9]])

In [36]:
np.diagflat([1,2],2)

array([[0, 0, 1, 0],
       [0, 0, 0, 2],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [38]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [40]:
np.tri(5, 5, -1, dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [41]:
#return a Lower triangle of an array.

In [45]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)


array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [46]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
#return Upper triangle of an array.

In [49]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# Random number generation

In [1]:
print("Random number generation (from Uniform distribution)")
import numpy as np
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.99811788 0.67808247 0.86162557]
 [0.2930166  0.66797871 0.99822993]]


In [4]:
print(np.random.rand(3,3,3))

[[[0.38496982 0.04214318 0.82198571]
  [0.40945167 0.89499599 0.46637091]
  [0.98102779 0.54197414 0.86490841]]

 [[0.6850261  0.05336401 0.60491697]
  [0.86866577 0.52810842 0.35759892]
  [0.25718824 0.33286112 0.76902707]]

 [[0.75139321 0.48323403 0.93779518]
  [0.59007474 0.23909302 0.51904944]
  [0.79708502 0.75502858 0.74803733]]]


In [5]:
np.random.randn(2,3)   #this function is well explained in statistic class

array([[ 0.17374386, -0.92716937,  0.60215274],
       [ 0.78758452,  0.00678143,  0.83727353]])

In [12]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
np.random.randint(1,10)

Random integer vector: 9

Random integer matrix


5

In [17]:
np.random.randint(1,100,(4,5,5))

array([[[55, 22, 53, 66, 13],
        [53,  4, 47, 79, 15],
        [18, 63, 72,  4, 26],
        [54, 16,  8, 86, 64],
        [29,  7, 84, 31, 29]],

       [[67,  4, 85, 40, 44],
        [52, 30, 35,  9, 51],
        [87, 84, 53, 75,  9],
        [51, 61, 30, 66, 40],
        [15, 86, 64, 26, 33]],

       [[40, 68, 38, 59, 48],
        [65, 22, 37, 32, 34],
        [62, 27, 96, 21, 62],
        [61, 24, 86, 83, 73],
        [49, 70, 74, 35, 11]],

       [[ 4, 63, 97, 50, 96],
        [61, 54, 27, 79, 22],
        [97, 98,  2, 42, 97],
        [50, 74, 29, 46, 62],
        [21, 30,  2, 90, 28]]])

In [18]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[51 66 62 43]
 [26 16 14 83]
 [57 12  6 86]
 [56 32 81 14]]

20 samples drawn from a dice throw: [4 5 6 5 3 6 1 6 2 3 3 2 1 6 6 6 1 1 6 1]


# Reshaping

In [8]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
b
c = a.reshape(6,-19878)
b



array([[[97, 69, 88, 80, 62],
        [ 9, 95,  9, 24, 89],
        [64, 71, 43, 80,  5]],

       [[50, 18, 88, 25, 95],
        [13, 52, 53, 34, 84],
        [75, 54, 55, 48, 54]]])

In [5]:
c

array([[15,  7, 50,  5, 76],
       [19, 24, 78, 49, 20],
       [16,  9, 41, 83, 49],
       [92, 95, 20, 15, 18],
       [66, 95,  3, 37, 90],
       [58, 73, 65, 88, 11]])

In [6]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [9]:
import numpy as np

A = ri(1,100,30) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [92  4 61 34 21  7 13 48 70  7 39  8  8 66 28 79 66 37 96 83 18 75 65  2
 22 40 37 62 65  6]

Here is the sorted vector
 -------------------------------------------------- 
 [ 2  4  6  7  7  8  8 13 18 21 22 28 34 37 37 39 40 48 61 62 65 65 66 66
 70 75 79 83 92 96]


In [17]:
z=A.reshape(6,5)
z

array([[26, 66, 49, 96, 42],
       [74, 36, 84, 78, 88],
       [41,  4, 48,  1, 20],
       [53, 40, 37, 10, 14],
       [71, 75, 32, 45, 34],
       [89, 32, 35, 98,  3]])

In [16]:
np.sort(z,axis=1)    #each data in column get sorted with axis=1

array([[26, 42, 49, 66, 96],
       [36, 74, 78, 84, 88],
       [ 1,  4, 20, 41, 48],
       [10, 14, 37, 40, 53],
       [32, 34, 45, 71, 75],
       [ 3, 32, 35, 89, 98]])

In [19]:
np.sort(z,axis=0)    #each data in row get sorted with axis=0

array([[26,  4, 32,  1,  3],
       [41, 32, 35, 10, 14],
       [53, 36, 37, 45, 20],
       [71, 40, 48, 78, 34],
       [74, 66, 49, 96, 42],
       [89, 75, 84, 98, 88]])

In [11]:
print("Max of a:", A.max())


Max of a: 96


In [23]:
b=A.reshape(5,6)
b

array([[92,  4, 61, 34, 21,  7],
       [13, 48, 70,  7, 39,  8],
       [ 8, 66, 28, 79, 66, 37],
       [96, 83, 18, 75, 65,  2],
       [22, 40, 37, 62, 65,  6]])

In [19]:
print('max no. at location ',A.argmax())

max location  18


In [27]:
c=b.argmax(axis=1)    #column wise max data axis=1
print(c)

[0 2 3 0 4]


In [28]:
c=b.argmax(axis=0)    #row wise max data axis=1
print(c)

[3 3 1 2 2 2]


In [33]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [34]:
arr[7]

7

In [37]:
arr[3:6]

array([3, 4, 5])

In [38]:
arr[:4]

array([0, 1, 2, 3])

In [39]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [2 4 9]


In [1]:
import numpy as np 
from numpy.random import randint as ri
mat = np.array(ri(10,100,45)).reshape(3,5,3)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

Matrix of random 2-digit numbers
--------------------------------
 [[[14 49 61]
  [15 36 77]
  [24 69 71]
  [59 11 29]
  [23 90 22]]

 [[94 86 20]
  [96 22 44]
  [33 92 48]
  [67 28 72]
  [67 88 62]]

 [[87 34 99]
  [95 71 46]
  [69 54 18]
  [45 80 34]
  [23 65 48]]]


In [7]:
mat[0][2]

array([22, 56, 11])

In [4]:
mat[0:2,[0,4]]  # 0:2 this means array at 0th and 1st position. and [0,4] means row 0 and 4

array([[[79, 98, 73],
        [56, 74, 31]],

       [[19, 49, 76],
        [22, 12, 92]]])

In [8]:
mat[0:2][0:2,3:]

array([[[61, 72, 73],
        [56, 74, 31]],

       [[36, 20, 16],
        [22, 12, 92]]])

In [30]:
for i in range(3):
    print(mat[i][0:2,:])

[[18 60 83]
 [40 32 21]]
[[13 41 17]
 [14 13 33]]
[[28 69 30]
 [17 80 59]]


In [31]:
mat[0:3,[1,3]]

array([[[40, 32, 21],
        [68, 83, 21]],

       [[14, 13, 33],
        [11, 89, 65]],

       [[17, 80, 59],
        [24, 48, 41]]])

In [10]:
mat[1:3,3:5]

array([[[36, 20, 16],
        [22, 12, 92]],

       [[81, 37, 75],
        [59, 67, 10]]])

In [4]:
mat

array([[[14, 49, 61],
        [15, 36, 77],
        [24, 69, 71],
        [59, 11, 29],
        [23, 90, 22]],

       [[94, 86, 20],
        [96, 22, 44],
        [33, 92, 48],
        [67, 28, 72],
        [67, 88, 62]],

       [[87, 34, 99],
        [95, 71, 46],
        [69, 54, 18],
        [45, 80, 34],
        [23, 65, 48]]])

In [6]:
mat[1:3,3:5]

array([[[67, 28, 72],
        [67, 88, 62]],

       [[45, 80, 34],
        [23, 65, 48]]])

In [15]:
mat[1:3,3:5,0:2]     #format mat[matrix no,row from ,column from]

array([[[67, 28],
        [67, 88]],

       [[45, 80],
        [23, 65]]])

#Subseting

In [43]:
mat = np.array(ri(10,100,45).reshape(3,5,3))
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[[12 60 31]
  [27 91 47]
  [41 97 73]
  [23 26 23]
  [29 71 60]]

 [[61 85 83]
  [95 57 29]
  [39 45 38]
  [24 98 91]
  [50 90 76]]

 [[33 51 34]
  [95 71 82]
  [70 96 86]
  [95 74 14]
  [31 93 48]]]


array([[[False,  True, False],
        [False,  True, False],
        [False,  True,  True],
        [False, False, False],
        [False,  True,  True]],

       [[ True,  True,  True],
        [ True,  True, False],
        [False, False, False],
        [False,  True,  True],
        [False,  True,  True]],

       [[False,  True, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True, False],
        [False,  True, False]]])

In [46]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [60 91 97 73 71 60 61 85 83 95 57 98 91 90 76 51 95 71 82 70 96 86 95 74
 93]


# Universal Functions

In [58]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[1 4 4]
 [4 2 7]
 [9 7 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 4 9]
 [2 9 1]
 [3 1 5]]


In [59]:
mat1*mat2

array([[ 8, 16, 36],
       [ 8, 18,  7],
       [27,  7, 25]])

In [60]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 28  44  33]
 [ 57  41  73]
 [101 104 113]]


In [61]:
print("\nDivision\n------------------\n", mat1/2)


Division
------------------
 [[0.5 2.  2. ]
 [2.  1.  3.5]
 [4.5 3.5 2.5]]


In [62]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[  1  64  64]
 [ 64   8 343]
 [729 343 125]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[  1  64  64]
 [ 64   8 343]
 [729 343 125]]


Broadcasting

In [64]:
start = np.zeros((4,4))
start= start+100
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])

In [65]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [66]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [67]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [3]:
from numpy import random

In [9]:
a=random.randn(100)
a

array([ 0.78975642,  0.46768597,  3.08050293,  0.32018389,  0.93422381,
        0.76649185, -0.98174012, -0.07605357, -0.1525112 , -1.55136287,
        0.49302578, -2.17314264,  0.17873277,  0.24856696,  0.93678216,
       -2.15887031, -1.02604399, -0.52255458,  0.34085114,  2.28844948,
        0.52807039, -2.34389932,  1.16656521,  0.24917333,  0.61399883,
       -0.05231145, -0.55518125,  1.0090298 , -2.43248556,  1.8757617 ,
        0.51364435,  0.07948592,  1.43198395,  0.37866654,  2.0202758 ,
        0.19540956,  0.09311948,  0.03608424, -1.43124432,  0.29504244,
        1.00749037, -0.80125841, -0.03335584,  0.64601804,  0.07659075,
       -0.04467684, -0.43233713,  1.32426511,  0.3226459 , -1.71856927,
       -0.25215506,  0.32872941, -0.76689465,  0.11765695, -1.97309012,
        1.53660922,  0.5367339 , -0.97699859, -0.08034589,  1.05716549,
        1.29989882,  0.0817064 , -0.41776754,  0.7378802 , -1.00302141,
        0.14400201, -0.42264271,  1.61901292,  0.45303195, -1.40

In [15]:
a.min()


-2.432485557026034